version: '3.4'

services:

  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
    - NET_ADMIN
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Europe/Moscow
    - URL=89-108-88-127.cloudvps.regruhosting.ru # change for your domain
    - EMAIL=ant1b0t@yandex.ru # optional
    - EXTRA_DOMAINS=89-108-88-127.cloudvps.regruhosting.ru # change for your domain
    volumes:
    - /app/swag:/config
    ports:
    - 443:443
    - 80:80
    restart: unless-stopped

  db:
    image: postgres:latest
    container_name: platform-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DrivingSchool_PROD_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DrivingSchool_PROD_POSTGRES_PASSWORD}
      POSTGRES_DB: ${DrivingSchool_PROD_POSTGRES_DB}
    ports:
      - '7433:7432'
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./migrations/:/docker-entrypoint-initdb.d/

  drivingschoolplatform.api:
    image: ${DOCKER_REGISTRY-}drivingschoolplatformapi
    build:
      context: .
      dockerfile: DrivingSchoolPlatform.Api/Dockerfile
    depends_on:
      - db
      - swag
    ports:
      - '8081:8081'
    environment:
      - ASPNETCORE_URLS=https://+:8081

  drivingschoolplatform:
    image: ${DOCKER_REGISTRY-}drivingschoolplatform
    build:
      context: .
      dockerfile: DrivingSchoolPlatform/DrivingSchoolPlatform/Dockerfile
    depends_on:
      - swag
      - drivingschoolplatform.api
    ports:
      - '8080:8080'
    environment:
      - ASPNETCORE_URLS=https://+:8080

volumes:
  db-data:
    driver: local

networks:
  default:
    name: drivingschool-network

