version: '3.4'

services:

  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
    - NET_ADMIN
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Europe/Moscow
    - URL=89-108-88-127.cloudvps.regruhosting.ru # change for your domain
    - VALIDATION=http
    - EMAIL=ant1b0t@yandex.ru # optional
    - EXTRA_DOMAINS=89-108-88-127.cloudvps.regruhosting.ru # change for your domain
    volumes:
    - ./config:/config
    ports:
    - 443:8080
    - 80:80
    restart: unless-stopped

  db:
    image: postgres:latest
    container_name: platform-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DrivingSchool_PROD_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DrivingSchool_PROD_POSTGRES_PASSWORD}
      POSTGRES_DB: ${DrivingSchool_PROD_POSTGRES_DB}
    ports:
      - '7433:7432'
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./migrations/:/docker-entrypoint-initdb.d/

  drivingschoolplatform.api:
    image: ${DOCKER_REGISTRY-}drivingschoolplatformapi
    build:
      context: .
      dockerfile: DrivingSchoolPlatform.Api/Dockerfile
    depends_on:
      - db
    ports:
      - '8081:8081'
    environment:
      - VIRTUAL_HOST=89-108-88-127.cloudvps.regruhosting.ru
      - LETSENCRYPT_HOST=89-108-88-127.cloudvps.regruhosting.ru

  drivingschoolplatform:
    image: ${DOCKER_REGISTRY-}drivingschoolplatform
    build:
      context: .
      dockerfile: DrivingSchoolPlatform/DrivingSchoolPlatform/Dockerfile
    depends_on:
      - drivingschoolplatform.api
    ports:
      - '8080:8080'
    environment:
      - VIRTUAL_HOST=89-108-88-127.cloudvps.regruhosting.ru
      - LETSENCRYPT_HOST=89-108-88-127.cloudvps.regruhosting.ru
      
volumes:
  conf:
    driver: local
  db-data:
    driver: local

networks:
  default:
    name: drivingschool-network

