version: '3.4'

services:

  nginx:
    container_name: nginx
    image: nginxproxy/nginx-proxy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/vhost:/etc/nginx/vhost.d
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  letsencrypt-companion:
    container_name: letsencrypt-companion
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: unless-stopped
    volumes_from:
        - nginx
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./nginx/acme:/etc/acme.sh
    environment:
        DEFAULT_EMAIL: ant1b0t@yandex.ru

  db:
    image: postgres:latest
    container_name: platform-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DrivingSchool_PROD_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DrivingSchool_PROD_POSTGRES_PASSWORD}
      POSTGRES_DB: ${DrivingSchool_PROD_POSTGRES_DB}
    ports:
      - '7433:7432'
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./migrations/:/docker-entrypoint-initdb.d/

  drivingschoolplatform.api:
    image: ${DOCKER_REGISTRY-}drivingschoolplatformapi
    build:
      context: .
      dockerfile: DrivingSchoolPlatform.Api/Dockerfile
    depends_on:
      - db
    ports:
      - '8081:8081'
    environment:
      - ASPNETCORE_URLS=http://+:8081
      - VIRTUAL_HOST=89-108-88-127.cloudvps.regruhosting.ru
      - LETSENCRYPT_HOST=89-108-88-127.cloudvps.regruhosting.ru

  drivingschoolplatform:
    image: ${DOCKER_REGISTRY-}drivingschoolplatform
    build:
      context: .
      dockerfile: DrivingSchoolPlatform/DrivingSchoolPlatform/Dockerfile
    depends_on:
      - drivingschoolplatform.api
    ports:
      - '8080:8080'
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - VIRTUAL_HOST=89-108-88-127.cloudvps.regruhosting.ru
      - LETSENCRYPT_HOST=89-108-88-127.cloudvps.regruhosting.ru

volumes:
  db-data:
    driver: local

networks:
  default:
    name: drivingschool-network

